name: app
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ">=2.18.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  provider: ^6.1.2  # Añade la librería provider para la gestión del estado
  http: ^1.2.2  # Añade la librería http para realizar las solicitudes a la API
  google_maps_flutter: ^2.9.0
  flutter_polyline_points: ^2.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
